package se.kth.sda6.perflow.projects;

import javax.persistence.*;

@Entity
@Table(name = "project")
public class Project {
    //General purpose related fields
    @Id
    @Column (name = "project-id")
    @GeneratedValue (strategy = GenerationType.IDENTITY)
    private long projectId; //To be used internally in the software and DB

    @Column (name = "project-unique-number")
    private String projectUniqueNumber; //To be provided by the user

    @Column (name = "project-name")
    private String projectName;

    //Scheduling related fields
    @Column (name = "duration")
    private int duration;

    @Column (name = "budget")
    private double budget;

    @Column (name = "peak-interval")
    private int peakInterval;

    @Column (name = "first-pv")
    private double firstPV; //First planned value

    @Column (name = "last-pv")
    private double lastPV;  //Last planned value

    //Financial related fields
    @Column (name = "adv-payment")
    private double advPayment; //The advance payment

    @Column (name = "perf-bond")
    private double perfBond;   //The performance bond, it's a percentage value start from zero & < 1

    @Column (name = "credit-time")
    private int creditTime; //The period allowed after the submit of payment to get paid

    @Column (name = "discount-rate")
    private double discountRate; //This percentage value showing how much the money loosing their value by the time


    public Project(String projectUniqueNumber, String projectName, int duration, double budget, int peakInterval, double firstPV, double lastPV, double advPayment, double perfBond, int creditTime, double discountRate) {
        this.projectUniqueNumber = projectUniqueNumber;
        this.projectName = projectName;
        this.duration = duration;
        this.budget = budget;
        this.peakInterval = peakInterval;
        this.firstPV = firstPV;
        this.lastPV = lastPV;
        this.advPayment = advPayment;
        this.perfBond = perfBond;
        this.creditTime = creditTime;
        this.discountRate = discountRate;
    }

    public long getProjectId() {
        return projectId;
    }

    //@Warning projectId should be autogenerated by the DB, therefore the setter maybe removed
    public void setProjectId(long projectId) {
        this.projectId = projectId;
    }

    public String getProjectUniqueNumber() {
        return projectUniqueNumber;
    }

    //@Warning projectUniqueNumber should be assured that it's unique before assigning it to the field
    public void setProjectUniqueNumber(String projectUniqueNumber) {
        this.projectUniqueNumber = projectUniqueNumber;
    }

    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public int getDuration() {
        return duration;
    }

    public void setDuration(int duration) {
        this.duration = duration;
    }

    public double getBudget() {
        return budget;
    }

    public void setBudget(double budget) {
        this.budget = budget;
    }

    public int getPeakInterval() {
        return peakInterval;
    }

    public void setPeakInterval(int peakInterval) {
        this.peakInterval = peakInterval;
    }

    public double getFirstPV() {
        return firstPV;
    }

    public void setFirstPV(double firstPV) {
        this.firstPV = firstPV;
    }

    public double getLastPV() {
        return lastPV;
    }

    public void setLastPV(double lastPV) {
        this.lastPV = lastPV;
    }

    public double getAdvPayment() {
        return advPayment;
    }

    public void setAdvPayment(double advPayment) {
        this.advPayment = advPayment;
    }

    public double getPerfBond() {
        return perfBond;
    }

    public void setPerfBond(double perfBond) {
        this.perfBond = perfBond;
    }

    public int getCreditTime() {
        return creditTime;
    }

    public void setCreditTime(int creditTime) {
        this.creditTime = creditTime;
    }

    public double getDiscountRate() {
        return discountRate;
    }

    public void setDiscountRate(double discountRate) {
        this.discountRate = discountRate;
    }
}
